### ISSUE TITLE
Public roadmap

### ISSUE THREAD

**Issue by equinusocio** [contactlab/design-system#19]
Hi all, this is our public roadmap <kbd>@ July 4 2018.</kbd>
> The striked out elements are excluded from the first phase.

## UI INVENTORY
- [x] **Colors**
- [x] **Typography**
- [x] **Spacing Scale**
- [x] **Type Scale**
- [x] **Elevations**
- [x] **Radius**
- [x] **Icons Library (ikonograph)**
- [ ] ~**Imagery**~
- [ ] ~**Themes**~

## MOTION
- [x] **Duration & Easings**
_Easing curves and duration patterns to create smooth and consistent motion._
- [ ] ~**Choreography**~
_Motion guides to help user’s focus through interactions by sharing elements across transitions._

## LAYOUTS
- [x] **Structures**
- [x] **Responsive UI**
- [ ] ~**Grids**~
_This UI guidance includes a flexible grid that ensures consistency across layouts, breakpoint details about how content reflows on different screens, and a description of how an app can scale from small to extra-large screens._

## UI COMPONENTS
- **Components design**
  - [x] Typography
  - [x] Buttons
  - [x] Buttons group
  - [x] Sliders
  - [x] Avatars
  - [x] Details
  - [x] Tables
  - [x] Progress
  - [x] Bullets
  - [x] Spinner
  - [x] Tabs
  - [x] Text fields
  - [x] Toggles (radio, check, switch)
  - [x] Tooltips
  - [x] Balloons
  - [x] Selects (single, multiple)
  - [x] Chips
  - [x] Icon toggle
  - [x] Datalist
  - [x] Date picker
  - [x] Pagination
  - [ ] ~Time Picker~
  - [x] Dividers
  - [x] Longpress buttons
  - [x] Modals
  - [x] Cards
  - [x] (Un)Ordered Lists
  - [x] Menu
  - [ ] ~Popovers~
  - [x] Snackbars
  - [x] Steppers
  - [ ] ~Bottom Sheets~
  - [ ] ~Bottom navigation (?)~

---

- **Components development**
  - [ ] **Typography**
  - [ ] **Buttons**
  - [ ] Buttons group
  - [ ] Sliders
  - [ ] **Avatars**
  - [ ] **Details**
  - [ ] **Tables**
  - [ ] Progress
  - [ ] Bullets
  - [ ] **Spinner**
  - [ ] **Tabs**
  - [ ] **Text fields**
  - [ ] **Toggles (radio, check)**
  - [ ] **Switch**
  - [ ] **Tooltips**
  - [ ] Balloons
  - [ ] **Selects (single, multiple)**
  - [ ] **Chips**
  - [ ] Icon toggle
  - [ ] **Datalist**
  - [ ] **Date picker**
  - [ ] **Pagination**
  - [ ] Dividers
  - [ ] **Modals**
  - [ ] Cards
  - [ ] (Un)Ordered Lists
  - [ ] **Menu (and Menu Item)**
  - [ ] **Snackbars**
  - [ ] Steppers

## PATTERNS
- [x] **Confirmation & acknowledgement**
> - [x] **Application Errors**
> _Errors occur when an app fails to complete an expected action._
> - [x] **Inform & Warn**
> _When a user invokes an action in your app, confirm or acknowledge that action through text._

- [x] **Empty states**
_Empty states occur when an item’s content can’t be shown._

- [ ] ~**Loading content and images**~
_Content may load with a placeholder element. Images, including illustrations and photographs, may load in three phases_

- [ ] ~**Navigations**~
_Navigation guides users through different parts of your app._

- [ ] ~**Notifications**~
_In-App notifications status_

- [ ] ~**Forms**~
_In-App notifications status_

- [ ] ~**Scrolling techniques**~
_Scrolling techniques affect how content scrolls in relation to UI elements_

- [x] **Search**
_Search allows users to locate app content quickly._
> - [X] **Paginations**
> _Pagination is the process of dividing a document into discrete pages._
> - [X] ~**Advanced search**~
> _The advanced search allows you to build structured queries._

- [ ] ~**Settings**~
_App settings let users indicate preferences in the proper way in relation to the data type_

## COMMUNICATION
- [ ] ~**Writing**~
- [ ] ~**Onboarding**~
Onboarding, often referred to as a “warm welcome,” is the first experience new users have with your product. Focus your onboarding on retaining new users by using one of these patterns.
- [ ] ~**Feature discovery**~
_Provide value and improve engagement by introducing users to new features and functionality at relevant moments._

**Comment by giotramu** [comment]
# UXD Elements

**Native UXD Elements**
```
Basic Tables
Basic Form Elements
├─ Text fields
├─ Toggles (Radio, Check)
└─ Selects (Single, Multiple)
Buttons
```
---
**Custom UXD Elements**
```
Advanced Tables
Advanced Form Elements
├─ Toggles (Switch)
├─ Autocomplete
├─ Date picker
└─ Time Picker
Sliders
Buttons group
Tags
Foldings
Progress
Spinner
Tags
Tabs
Pills
Tooltips
Toast
Chips
Dividers
Lists
Menu
Popovers
Snackbars
Steppers
Bottom Sheets
Bottom navigation
```
